import { Inter, JetBrains_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/provider/AuthProvider";
import QueryProvider from "@/provider/QueryProvider";
import { Toaster } from "react-hot-toast";
import ThemeInitializer from "@/components/shared/theme/ThemeInitializer";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-display",
});

const jetBrains_mono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`
        ${inter.variable}
        ${playfair.variable}
        ${jetBrains_mono.variable}
        h-full
        antialiased
      `}
    >
      <body className="bg-surface text-on-surface font-body-md relative">
        <QueryProvider>
          <AuthProvider>
            <ThemeInitializer />
            {children}
            <Toaster position="top-right" />
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
